### ISSUE TITLE
老哥，data这个值我怎么知道传什么，如果是一个全新的合约项目交互的话，还有方便加个微信交流吗

### ISSUE THREAD

**Issue by 624133262** [junjie9021/simple-airdrop-demo#3]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/28002830/227763373-dc8be57d-4cce-4505-9d22-5582962a3c44.png">

**Comment by junjie9021** [comment]
data值要学习下智能合约交互的，个人资料有tg交流群的哈

624133262 ***@***.***> 于2023年3月26日周日 16:08写道：

**Comment by 624133262** [comment]
刚才人机验证没过。。。。饿 明天能再次加吗

**Comment by junjie9021** [comment]
可以的，加上验证就行

624133262 ***@***.***> 于2023年3月28日周二 15:43写道：
